version: '3'
services:

  response:
    build:
      context: .
      dockerfile: Dockerfile.local
    image: response
    container_name: response
    command:
      - wait-for-it.sh
      - db:5432
      - -- 
      - python
      - ./manage.py
      - runserver
      - 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - ./:/code
    stdin_open: true
    tty: true
    depends_on: 
      - db
      - migrations

  migrations:
    build:
      context: .
      dockerfile: Dockerfile.local
    image: response
    container_name: migrations
    command:
      - wait-for-it.sh
      - db:5432
      - -- 
      - python
      - ./manage.py
      - migrate
    env_file: .env
    volumes:
      - ./:/code
    tty: true
    depends_on: 
      - db


  db:
    image: "postgres:11.2"
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  # ngrok:
  #   image: gtriggiano/ngrok-tunnel
  #   container_name: ngrok
  #   environment:
  #     TARGET_HOST: "response"
  #     TARGET_PORT: 8000
  #   ports:
  #     - "4040:4040"
  #   depends_on:
  #     - response

volumes:
  postgres_data: